@startuml FasterCodingMatrixLibrary

package FasterCodingMatrixLibrary <<Frame>> {

class Matrix {
    - _matrix: std::vector<vector<int>>

    + Matrix(int width, int height)
    + Matrix(std::vector<std::vector<int>> matrix)
    + ~Matrix()
    + operator*(Matrix& matrix): Matrix*
    + operator*(Vector& vector): Vector*
    + getValueAt(int& x, int& y): int
    + setValueAt(int& x, int& y, int& value): void
    + getWidth(): size_t
    + getHeight(): size_t
    + print(): void
}

class Vector {
    - _vector: vector<int>

    + Vector(std::vector<int>)
    + ~Vector()
    + getSize(): size_t
}

}

@enduml